<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>ICS22_get_gov_proposals_proposalId_votes_voter</name>
   <tag></tag>
   <elementGuidId>1c00b5fa-f5cb-42d3-b783-581796535109</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>HTTP://localhost:1317/gov/proposals/${proposalId}${/votes/}${voter}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceFunction></soapServiceFunction>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1b7d3450-f8c6-4107-a8f5-ea49200c29ed</id>
      <masked>false</masked>
      <name>proposalId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>737f0270-5453-4bfd-aa60-a2c85703998b</id>
      <masked>false</masked>
      <name>voter</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
